name: hardcoded_strings_lint
description: A custom Flutter lint rule that identifies and prevents hardcoded strings in widget constructors, promoting better internationalization practices and code maintainability.
version: 2.0.0
homepage: https://github.com/ShahSomething
repository: https://github.com/ShahSomething/hardcoded_strings_lint
issue_tracker: https://github.com/ShahSomething/hardcoded_strings_lint/issues

environment:
  sdk: ^3.11.0

dependencies:
  analysis_server_plugin: ^0.3.15
  analyzer: ^13.0.0

dev_dependencies:
  analyzer_testing: ^0.2.6
  lints: ^6.0.0
  test: ^1.26.3
  test_reflective_loader: ^0.4.0
