name: hardcoded_strings_lint
description: A custom Flutter lint rule that identifies and prevents hardcoded strings in widget constructors, promoting better internationalization practices and code maintainability.
version: 1.0.4
homepage: https://github.com/ShahSomething
repository: https://github.com/ShahSomething/hardcoded_strings_lint
issue_tracker: https://github.com/ShahSomething/hardcoded_strings_lint/issues

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  custom_lint_builder: ^0.8.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
